#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build -TEST-

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
      staging_dir:
        description: 'staging_dir to Actions 0:disable,1:use not upload,2:use and upload'
        required: false
        default: '2'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  IO_URL: https://wzlcm:${{ secrets.ACCESS_TOKEN}}@github.com/wzlcm/wzlcm.github.io.git
  DL_BRANCH: test
  BUILD_BRANCH: build
  STAGEING_BRANCH: staging_dir
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: config/Qualcomm/gdock.config
  DIY_P1_SH: scripts/diy-part1-1.sh
  DIY_P2_SH: scripts/diy-part2-1.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_DOWNLOAD: true
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        sudo git lfs install

        
